---
- name: Tratando arquivos Selinux e HTTPD
  hosts: web
  remote_user: ansible-core
  become: yes

  tasks:
    - name: 2
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX=
    line=SELINUX=enforcing

    - name: 3
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen "
    insertafter="^#Listen " line="Listen 8080"
      
 #v1
