---
- name: Trabalhando com  saida de comandos
  hosts: web
  remote_user: ansible
  become: yes
  
  tasks:
  
    - name: Saida do comando httpd
      #shell: httpd -v|grep version|awk '{print $3}'|cut -f2 -d'/'
      shell: uptime
      register: result
    
    - debug: var=result
